esphome:
  name: issmonitor
  platform: ESP32
  board: m5stack-core-esp32

# Enable logging
logger:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "ISSMonitor Fallback Hotspot"
    password: "4uOZaAy4XLD5"

captive_portal:

color:
  - id: RED
    red: 100%
    green: 0%
    blue: 0%
  - id: BLUE
    red: 0%
    green: 0%
    blue: 100%
  - id: WHITE
    red: 100%
    green: 100%
    blue: 100%

# https://github.com/m5stack/M5Stack

spi:
  clk_pin: GPIO18
  mosi_pin: GPIO23
  miso_pin: GPIO19

display:
  - platform: ili9341
    model: M5STACK
    cs_pin: GPIO14
    dc_pin: GPIO27
    led_pin: GPIO32
    reset_pin: GPIO33

    lambda: |-
      // Turn the whole display on.
      it.fill(COLOR_ON);

      // Turn a single pixel off at [50,60]
      it.draw_pixel_at(50, 60, COLOR_OFF);

      // Turn off a whole display portion.
      it.rectangle(50, 50, 30, 42, COLOR_OFF);

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO39
      inverted: true
    name: BtnA

  - platform: gpio
    pin:
      number: GPIO38
      inverted: true
    name: BtnB

  - platform: gpio
    pin:
      number: GPIO37
      inverted: true
    name: BtnC
